import torch as pt

BASE_INT_TYPE = pt.int32
BASE_REAL_TYPE = pt.double
BASE_COMPLEX_TYPE = pt.cdouble

DEFAULT_INIT_SCALE = 0.001

BACKENDS = ('TORCH', 'SCIPY')

DEFAULT_SVD_BACKEND = 'TORCH'
DEFAULT_BACKPROP_BACKEND = 'TORCH'

DEFAULT_MAX_BOND_DIM = 100
DEFAULT_CUTOFF = 1e-15
DEFAULT_LORENTZIAN = 1e-12

DEFAULT_SR_REGULISER = 1e-2
